version: '2'

services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ba02edad58268b77ada2981760fc8f5cf5401f84c822e14f489721ec275eb023_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ba02edad58268b77ada2981760fc8f5cf5401f84c822e14f489721ec275eb023_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1

    extra_hosts:
      - "zookeeper0:10.200.156.202"
      - "zookeeper1:10.200.156.203"
      - "zookeeper2:10.200.156.204"
      - "kafka0:10.200.156.202"
      - "kafka1:10.200.156.203"
      - "kafka2:10.200.156.204"
      - "kafka3:10.200.156.205"
      - "orderer.example.com:10.200.156.202"
      - "orderer1.example.com:10.200.156.203"
      - "orderer2.example.com:10.200.156.204"
      - "orderer3.example.com:10.200.156.205"
      - "ca1:10.200.156.202"
      - "peer0.org1.example.com:10.200.156.202"
      - "peer1.org1.example.com:10.200.156.202"
      - "ca2:10.200.156.203"
      - "peer0.org2.example.com:10.200.156.203"
      - "peer1.org2.example.com:10.200.156.203"
      - "ca3:10.200.156.204"
      - "peer0.org3.example.com:10.200.156.204"
      - "peer1.org3.example.com:10.200.156.204"
      






  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.example.com
    extra_hosts:
      - "zookeeper0:10.200.156.202"
      - "zookeeper1:10.200.156.203"
      - "zookeeper2:10.200.156.204"
      - "kafka0:10.200.156.202"
      - "kafka1:10.200.156.203"
      - "kafka2:10.200.156.204"
      - "kafka3:10.200.156.205"
      - "orderer.example.com:10.200.156.202"
      - "orderer1.example.com:10.200.156.203"
      - "orderer2.example.com:10.200.156.204"
      - "orderer3.example.com:10.200.156.205"
      - "ca1:10.200.156.202"
      - "peer0.org1.example.com:10.200.156.202"
      - "peer1.org1.example.com:10.200.156.202"
      - "ca2:10.200.156.203"
      - "peer0.org2.example.com:10.200.156.203"
      - "peer1.org2.example.com:10.200.156.203"
      - "ca3:10.200.156.204"
      - "peer0.org3.example.com:10.200.156.204"
      - "peer1.org3.example.com:10.200.156.204"

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.example.com

    extra_hosts:
      - "zookeeper0:10.200.156.202"
      - "zookeeper1:10.200.156.203"
      - "zookeeper2:10.200.156.204"
      - "kafka0:10.200.156.202"
      - "kafka1:10.200.156.203"
      - "kafka2:10.200.156.204"
      - "kafka3:10.200.156.205"
      - "orderer.example.com:10.200.156.202"
      - "orderer1.example.com:10.200.156.203"
      - "orderer2.example.com:10.200.156.204"
      - "orderer3.example.com:10.200.156.205"
      - "ca1:10.200.156.202"
      - "peer0.org1.example.com:10.200.156.202"
      - "peer1.org1.example.com:10.200.156.202"
      - "ca2:10.200.156.203"
      - "peer0.org2.example.com:10.200.156.203"
      - "peer1.org2.example.com:10.200.156.203"
      - "ca3:10.200.156.204"
      - "peer0.org3.example.com:10.200.156.204"
      - "peer1.org3.example.com:10.200.156.204"

  cli0:
    container_name: cli0
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    extra_hosts:
      - "zookeeper0:10.200.156.202"
      - "zookeeper1:10.200.156.203"
      - "zookeeper2:10.200.156.204"
      - "kafka0:10.200.156.202"
      - "kafka1:10.200.156.203"
      - "kafka2:10.200.156.204"
      - "kafka3:10.200.156.205"
      - "orderer.example.com:10.200.156.202"
      - "orderer1.example.com:10.200.156.203"
      - "orderer2.example.com:10.200.156.204"
      - "orderer3.example.com:10.200.156.205"
      - "ca1:10.200.156.202"
      - "peer0.org1.example.com:10.200.156.202"
      - "peer1.org1.example.com:10.200.156.202"
      - "ca2:10.200.156.203"
      - "peer0.org2.example.com:10.200.156.203"
      - "peer1.org2.example.com:10.200.156.203"
      - "ca3:10.200.156.204"
      - "peer0.org3.example.com:10.200.156.204"
      - "peer1.org3.example.com:10.200.156.204"

  cli1:
    container_name: cli1
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.org1.example.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    extra_hosts:
      - "zookeeper0:10.200.156.202"
      - "zookeeper1:10.200.156.203"
      - "zookeeper2:10.200.156.204"
      - "kafka0:10.200.156.202"
      - "kafka1:10.200.156.203"
      - "kafka2:10.200.156.204"
      - "kafka3:10.200.156.205"
      - "orderer.example.com:10.200.156.202"
      - "orderer1.example.com:10.200.156.203"
      - "orderer2.example.com:10.200.156.204"
      - "orderer3.example.com:10.200.156.205"
      - "ca1:10.200.156.202"
      - "peer0.org1.example.com:10.200.156.202"
      - "peer1.org1.example.com:10.200.156.202"
      - "ca2:10.200.156.203"
      - "peer0.org2.example.com:10.200.156.203"
      - "peer1.org2.example.com:10.200.156.203"
      - "ca3:10.200.156.204"
      - "peer0.org3.example.com:10.200.156.204"
      - "peer1.org3.example.com:10.200.156.204"

